languageCode = "en"
languageName = "English"
weight = 1
title = "Red Blowfish"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "My git-blog"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Noam Afergan"
  image = "img/avatar.png"
  headline = "4f3rg4n git-blog"
  bio = "A low-level junkie and CTF player"
   links = [
     { linkedin = "https://www.linkedin.com/in/noam-afergan-074176284/" },
     { github = "https://github.com/4f3rg4n" },
     { x-twitter = "https://twitter.com/4f3rg4n" }
   ]
